spring.application.name=Servio

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/servio}
spring.datasource.username=${DB_USER:servio}
spring.datasource.password=${DB_PASSWORD:servio}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
